name = str(input("Hello. What is your name? "))
age = input("Hi,"+ name +"! How old are you? ")
print("So you're " + age + ", eh? That's not very old.")
weight = float(input("How much do you weigh," + name+"? " ))
print(weight,"! Better keep that quiet!!")
income = float(input("Finally, what's your income," + name+"? " ))
print("Hopefully that is", income,"per hour and not per year!")
print("Well, thanks for answering my rude questions,",name,".")